" These things cause problems.
"inoremap jj <Esc>
"set hlsearch
"nnoremap <Esc><Esc> :noh<return><Esc>

set nocompatible
" vim7.2 intentionally makes * lamer for php.  wtf
autocmd FileType php setlocal iskeyword+=$

filetype on
syntax on
colorscheme ir_black
" This line has to be *after* `colorscheme`.
highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%80v.\+/

set number
set cursorline " Highlight current line.
set tw=79
set hidden
"set fo=tcqrb " does not work
set wrap
set wildmode=list:longest " autocompletion is bash like
set nojoinspaces  " Disable double space after punctuation. See Matthew
                  " Butterick's Practical Typography

" Indentation and tabs.
set autoindent
" If the 'expandtab' option is on, spaces will be used to fill the amount of
" whitespace of the tab.
set expandtab
" we explicitly don't use 'smarttab' and 'softtabstop'
set shiftwidth=4
set tabstop=4

"inoremap jj <Esc>
set hlsearch
set incsearch " incremental search
set ignorecase
set smartcase " don't ignore case when it's not only lowercase.
"nnoremap <Esc><Esc> :noh<return><Esc>
nnoremap + <C-w>+
nnoremap - <C-w>-
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-h> <C-w>h
map <C-l> <C-w>l
" maximize window
map <C-m> <C-w>_

" Status line.
set laststatus=2
"set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [ASCII=\%03.3b]\ [HEX=\%02.2B]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]


set viminfo='50,"50           " '=marks for x files, "=registers for x files
set scrolloff=5               " scroll offsett, min lines above/below cursor
set scrolljump=5              " jump 5 lines when running out of the screen
set sidescroll=10             " minumum columns to scroll horizontally
set showcmd                   " show command status
set showmatch                 " flashes matching paren when one is typed
set showmode                  " show editing mode in status (-- INSERT --)
set ruler                     " show cursor position

" not sure this is needed
set noerrorbells              " no bells in terminal

"other things (from
"http://b4winckler.wordpress.com/2009/07/10/a-minimal-vim-configuration/)
set backspace=indent,eol,start

" Make, TSV and Go files kind of do not like tabs to be expanded.
autocmd Filetype make setlocal noexpandtab tabstop=4
autocmd BufRead,BufNewFile,BufEnter *.tsv set noexpandtab tabstop=4
autocmd BufRead,BufNewFile,BufEnter *.go set noexpandtab tabstop=4

" When editing TeX abd HTML files, don't apply the usual textwidth rules.
" http://stackoverflow.com/questions/1413285
" http://vim.wikia.com/wiki/Word_wrap_without_line_breaks
autocmd BufNewFile,BufRead,BufEnter *.tex call SetNoWrapOptions()
autocmd Filetype html call SetNoWrapOptions()
function SetNoWrapOptions()
    highlight clear OverLength
    setlocal textwidth=0 wrapmargin=0
    setlocal linebreak
endfunction

" Simple way to handle folds (works well with Python at least.)
set foldmethod=indent
set foldlevel=99

" Moving by screen line instead of file line.
noremap <Up> gk
noremap! <Up> <C-O>gk
noremap <Down> gj
noremap! <Down> <C-O>gj
